import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

/// Service for managing daily pulse check-ins
///
/// A "Pulse Day" starts at 4:00 AM local time and resets daily.
/// Users can pulse once per Pulse Day by opening the app.
class PulseService {
  final SupabaseClient _supabase;

  PulseService(this._supabase);

  /// Calculate the start of the current Pulse Day (4:00 AM local time)
  ///
  /// If current time is >= 4:00 AM: Returns today at 4:00 AM
  /// If current time is < 4:00 AM: Returns yesterday at 4:00 AM
  DateTime getStartOfPulseDay() {
    final now = DateTime.now();
    final today4AM = DateTime(now.year, now.month, now.day, 4, 0, 0);

    if (now.isBefore(today4AM)) {
      // It's before 4 AM, so the Pulse Day started yesterday at 4 AM
      return today4AM.subtract(const Duration(days: 1));
    } else {
      // It's after 4 AM, so the Pulse Day started today at 4 AM
      return today4AM;
    }
  }

  /// Check if the current user has pulsed today (within current Pulse Day)
  ///
  /// Returns true if a pulse exists for the user since the start of the Pulse Day.
  Future<bool> hasPulsedToday() async {
    try {
      final user = _supabase.auth.currentUser;
      if (user == null) {
        throw Exception('No authenticated user found');
      }

      final startOfDay = getStartOfPulseDay();

      final response = await _supabase
          .from('daily_pulses')
          .select('id')
          .eq('user_id', user.id)
          .gte('created_at', startOfDay.toIso8601String())
          .count(CountOption.exact);

      return (response.count ?? 0) > 0;
    } catch (e) {
      // Log error and return false to allow graceful degradation
      print('Error checking pulse status: $e');
      return false;
    }
  }

  /// Send a pulse (insert a new row into daily_pulses table)
  ///
  /// Returns true if the pulse was sent successfully, false otherwise.
  Future<bool> sendPulse() async {
    try {
      final user = _supabase.auth.currentUser;
      if (user == null) {
        throw Exception('No authenticated user found');
      }

      await _supabase.from('daily_pulses').insert({
        'user_id': user.id,
        'status': 'active',
        // created_at is auto-generated by Supabase
      });

      return true;
    } catch (e) {
      // Log error and return false
      print('Error sending pulse: $e');
      return false;
    }
  }

  /// Check if user has pulsed today, and if not, send a pulse
  ///
  /// This is the main orchestration method called during app launch.
  /// Returns true if a pulse was sent, false if already pulsed today or error occurred.
  Future<bool> checkAndPulse() async {
    try {
      // Check if already pulsed today
      final alreadyPulsed = await hasPulsedToday();

      if (alreadyPulsed) {
        print('User has already pulsed today');
        return false; // Already pulsed, no action needed
      }

      // Send the pulse
      final success = await sendPulse();

      if (success) {
        print('Pulse sent successfully');
      } else {
        print('Failed to send pulse');
      }

      return success;
    } catch (e) {
      print('Error in checkAndPulse: $e');
      return false;
    }
  }
}

/// Riverpod provider for PulseService
///
/// Access this service using `ref.read(pulseServiceProvider)` or `ref.watch(pulseServiceProvider)`
final pulseServiceProvider = Provider<PulseService>((ref) {
  final supabase = Supabase.instance.client;
  return PulseService(supabase);
});
